 -- 19. Basic Select All Fields 
SELECT *
FROM   TOWNS;

SELECT *
FROM   DEPARTMENTS;

SELECT *
FROM   EMPLOYEES;

-- 20. Basic Select All Fields and Order Them
SELECT *
FROM   TOWNS
ORDER  BY 2 ASC;

SELECT *
FROM   DEPARTMENTS
ORDER  BY 2 ASC;

SELECT *
FROM   EMPLOYEES
ORDER  BY SALARY DESC;

-- 21. Basic Select Some Fields  
SELECT NAME
FROM   TOWNS
ORDER  BY NAME ASC;

SELECT NAME
FROM   DEPARTMENTS
ORDER  BY NAME ASC;

SELECT FIRSTNAME
       ,LASTNAME
       ,JOBTITLE
       ,SALARY
FROM   EMPLOYEES
ORDER  BY SALARY DESC;

-- 22. Increase Employees Salary 
UPDATE EMPLOYEES
SET    SALARY = ( 1.1 * SALARY )

SELECT SALARY
FROM   EMPLOYEES

-- 23. Decrease Tax Rate 
UPDATE PAYMENTS
SET    TAXRATE = ( 0.97 * TAXRATE )

SELECT TAXRATE
FROM   PAYMENTS

--  24. Delete All Records 
TRUNCATE TABLE OCCUPANCIES  