 CREATE DATABASE SOFTUNI

GO

USE SOFTUNI

GO

CREATE TABLE TOWNS
  (
     ID    INT IDENTITY(1, 1) PRIMARY KEY NOT NULL
     ,NAME NVARCHAR(255)
  )

CREATE TABLE ADDRESSES
  (
     ID           INT IDENTITY(1, 1) PRIMARY KEY NOT NULL
     ,ADDRESSTEXT NVARCHAR(255)
     ,TOWNID      INT NOT NULL
     FOREIGN KEY (TOWNID) REFERENCES TOWNS(ID)
  )

CREATE TABLE DEPARTMENTS
  (
     ID    INT IDENTITY(1, 1) PRIMARY KEY NOT NULL
     ,NAME NVARCHAR(255)
  )

CREATE TABLE EMPLOYEES
  (
     ID            INT IDENTITY(1, 1) PRIMARY KEY NOT NULL
     ,FIRSTNAME    NVARCHAR(255)
     ,MIDDLENAME   NVARCHAR(255)
     ,LASTNAME     NVARCHAR(255)
     ,JOBTITLE     NVARCHAR(255)
     ,DEPARTMENTID INT NOT NULL
     ,HIREDATE     DATE NOT NULL
     ,SALARY       DECIMAL(10, 2)
     ,ADDRESSID    INT NOT NULL
     FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENTS(ID),
     FOREIGN KEY (ADDRESSID) REFERENCES ADDRESSES(ID)
  )  